"""
ClearSky AI - XGBoost Training Pipeline

Trains 3 XGBoost regressors for 24h, 48h, 72h AQI forecasting.
Uses the dataset generated by data/collector.py.

Features:
  - Pollutants: pm25, pm10, no2, so2, o3, co
  - Weather: temperature, humidity, wind_speed, wind_direction, pressure, precipitation, uv_index
  - Time: hour, weekday, month, season
  - Engineered: rolling averages, risk flags

Usage:
  python model/trainer.py
"""

import os
import json
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

MODEL_DIR = os.path.dirname(__file__)
DATA_PATH = os.path.join(os.path.dirname(MODEL_DIR), "data", "training_data.json")

# ── EPA AQI Calculation (mirrors backend logic) ──────────────────
PM25_BP = [(0,12,0,50),(12.1,35.4,51,100),(35.5,55.4,101,150),(55.5,150.4,151,200),
           (150.5,250.4,201,300),(250.5,350.4,301,400),(350.5,500.4,401,500)]

def pm25_to_aqi(c):
    if c is None or np.isnan(c) or c < 0: return None
    for cl, ch, il, ih in PM25_BP:
        if cl <= c <= ch:
            return round(((ih - il) / (ch - cl)) * (c - cl) + il)
    return 500

# ── Feature Engineering ──────────────────────────────────────────
FEATURE_COLS = [
    "pm25", "pm10", "no2", "so2", "o3", "co",
    "temperature", "humidity", "wind_speed", "wind_direction",
    "pressure", "precipitation", "uv_index",
    "hour", "weekday", "month", "season",
    "pm25_rolling_6h", "pm25_rolling_24h",
    "temp_rolling_6h",
    "low_wind_flag", "high_humidity_flag", "smog_risk_flag",
]

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add rolling averages and risk flags."""
    df = df.copy()
    df.sort_values("timestamp", inplace=True)
    
    # Rolling averages (hourly data)
    df["pm25_rolling_6h"] = df["pm25"].rolling(window=6, min_periods=1).mean()
    df["pm25_rolling_24h"] = df["pm25"].rolling(window=24, min_periods=1).mean()
    df["temp_rolling_6h"] = df["temperature"].rolling(window=6, min_periods=1).mean()
    
    # Risk flags
    df["low_wind_flag"] = (df["wind_speed"] < 5).astype(int)
    df["high_humidity_flag"] = (df["humidity"] > 70).astype(int)
    df["smog_risk_flag"] = ((df["pm25"] > 50) & (df["wind_speed"] < 5) & (df["humidity"] > 60)).astype(int)
    
    return df


def create_targets(df: pd.DataFrame) -> pd.DataFrame:
    """Create target columns: AQI at +24h, +48h, +72h."""
    df = df.copy()
    # Compute current AQI from PM2.5 (dominant pollutant proxy)
    df["current_aqi"] = df["pm25"].apply(pm25_to_aqi)
    
    # Shift pm25 forward to create future targets, then convert to AQI
    df["target_24h"] = df["pm25"].shift(-24).apply(pm25_to_aqi)
    df["target_48h"] = df["pm25"].shift(-48).apply(pm25_to_aqi)
    df["target_72h"] = df["pm25"].shift(-72).apply(pm25_to_aqi)
    
    return df


# ── Training ─────────────────────────────────────────────────────
def train_model(X_train, y_train, X_val, y_val, name: str) -> xgb.XGBRegressor:
    """Train a single XGBoost regressor."""
    model = xgb.XGBRegressor(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        min_child_weight=3,
        random_state=42,
        n_jobs=-1,
    )
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )
    
    # Metrics
    preds = model.predict(X_val)
    mae = mean_absolute_error(y_val, preds)
    rmse = np.sqrt(mean_squared_error(y_val, preds))
    r2 = r2_score(y_val, preds)
    print(f"  {name}: MAE={mae:.2f}, RMSE={rmse:.2f}, R²={r2:.4f}")
    
    return model


def run_training():
    """Full training pipeline."""
    # Load data
    if not os.path.exists(DATA_PATH):
        print(f"Error: No training data found at {DATA_PATH}")
        print("   Run: python data/collector.py --city Hyderabad --days 365")
        return False
    
    with open(DATA_PATH) as f:
        raw = json.load(f)
    
    records = raw["records"]
    print(f"Stats: Loaded {len(records)} records for {raw.get('city', 'unknown')}")
    
    df = pd.DataFrame(records)
    
    # Fill missing values
    numeric_cols = ["pm25","pm10","no2","so2","o3","co","temperature","humidity",
                    "wind_speed","wind_direction","pressure","precipitation","uv_index"]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
            df[col] = df[col].interpolate(method="linear").fillna(df[col].median())
    
    # Engineer features
    df = engineer_features(df)
    df = create_targets(df)
    
    # Drop rows where targets are NaN (last 72 rows)
    df = df.dropna(subset=["target_24h", "target_48h", "target_72h"])
    
    if len(df) < 200:
        print(f"Warn: Only {len(df)} valid samples. Need at least 200 for reliable training.")
        print("  Consider collecting more days of data.")
    
    # Prepare features
    available_features = [c for c in FEATURE_COLS if c in df.columns]
    X = df[available_features].fillna(0)
    
    print(f"Setup: Features: {len(available_features)}, Samples: {len(X)}")
    
    # Train/val split (time-based — last 20% for validation)
    split_idx = int(len(X) * 0.8)
    X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
    
    models = {}
    for horizon, target_col in [("24h", "target_24h"), ("48h", "target_48h"), ("72h", "target_72h")]:
        y = df[target_col]
        y_train, y_val = y.iloc[:split_idx], y.iloc[split_idx:]
        
        print(f"\nTrain: Training {horizon} model...")
        model = train_model(X_train, y_train, X_val, y_val, horizon)
        models[horizon] = model
    
    # Save models
    for horizon, model in models.items():
        path = os.path.join(MODEL_DIR, f"xgb_{horizon}.json")
        model.save_model(path)
        print(f"Save: Saved {path}")
    
    # Save feature list for inference
    meta = {
        "features": available_features,
        "trained_at": pd.Timestamp.now().isoformat(),
        "samples": len(X),
        "city": raw.get("city", "unknown"),
    }
    with open(os.path.join(MODEL_DIR, "model_meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    
    print("\nOK: Training complete!")
    return True


if __name__ == "__main__":
    run_training()
